services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tg_diary
      POSTGRES_PASSWORD: tg_diary
      POSTGRES_DB: tg_diary
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: .
    depends_on:
      - db
    env_file:
      - .env.docker

volumes:
  db_data: